### ISSUE TITLE
No *data*.JSON file created

### ISSUE THREAD

**Issue by ikalogic** [mcred/jekyll-xml-source#1]
Hi,

First thank you very much for that plugin.

Unfortunately, I can't get it to work. I have no error codes, I installed all required dependencies. 

When I launch the localhost server, no any *.JSON files are created in my _data/ directory.

Any ideas?

**Comment by ikalogic** [comment]
Oops - stupid mistake on my end, works perfectly. sorry!

**Comment by mcred** [comment]
Glad it's working for you.
